### ISSUE TITLE
change SE locale to US/UK locale

### ISSUE THREAD

**Issue by achaido** [Open-Sustainability-Index/open-sustainability-index-frontend#23]
Currently it's thousand separators and decimals based on [sweden locale](https://www.localeplanet.com/icu/sv-SE/index.html), but makes more sense to base it on [US](https://www.localeplanet.com/java/en-US/index.html) or [UK](https://www.localeplanet.com/icu/en-GB/index.html) locale. Sorry for not being more specific in the first issue.

**Comment by hankmander** [comment]
We have US locale now as far as I can see.
