### ISSUE TITLE
Site name in <header>

### ISSUE THREAD

**Issue by achaido** [Open-Sustainability-Index/open-sustainability-index-frontend#5]
Currently, pages does not show [Open Sustainability Index] 
E.g. the API page only show [API] [opensustainabilityindex.org/api](opensustainabilityindex.org/api)

**Comment by tomsoderlund** [comment]
@achaido The formatting is currently `[PageName] – Open Sustainability Index`, is that ok?

![Image](https://github.com/Open-Sustainability-Index/open-sustainability-index-frontend/assets/1368668/2ee1db60-66e8-4040-85ef-f7dd30384463)
